project:
  type: website

website:
  title: "한밭대"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: penguin.qmd
        text: "펭귄 강의"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

